// Shared column-name constants for the local store's table definitions.
// One catalog so every table refers to a column by the same name.

export const COL = {
  id: 'id',
  sourceTool: 'source_tool',
  kind: 'kind',
  occurredAt: 'occurred_at',
  contentHash: 'content_hash',
  content: 'content',
  metadata: 'metadata',
  eventId: 'event_id',
  ruleId: 'rule_id',
  category: 'category',
  severity: 'severity',
  spanStart: 'span_start',
  spanEnd: 'span_end',
  maskedMatch: 'masked_match',
  actionTaken: 'action_taken',
  confidence: 'confidence',
  scope: 'scope',
  target: 'target',
  action: 'action',
  enabled: 'enabled',
  customKeywords: 'custom_keywords',
  // Recommended-actions columns
  title: 'title',
  status: 'status',
  name: 'name',
  createdAt: 'created_at',
  updatedAt: 'updated_at',
  // Installed-pack columns
  namespace: 'namespace',
  packId: 'pack_id',
  description: 'description',
  version: 'version',
  rulesJson: 'rules_json',
  recordedBy: 'recorded_by',
  open: 'open',
  policyId: 'policy_id',
  lastUsedAt: 'last_used_at',
  revokedAt: 'revoked_at',
  expiresAt: 'expires_at',
  // Detection exceptions columns
  valueFingerprint: 'value_fingerprint',
  keyVersion: 'key_version',
  maskedValue: 'masked_value',
  maxUses: 'max_uses',
  useCount: 'use_count',
  justification: 'justification',
  conditions: 'conditions',
  createdBy: 'created_by',
  createdVia: 'created_via',
  revokedBy: 'revoked_by',
  revokeReason: 'revoke_reason',
  // Meta data model — Inventory (existence dimension)
  objectType: 'object_type',
  location: 'location',
  hostId: 'host_id',
  attributes: 'attributes',
  firstSeen: 'first_seen',
  lastSeen: 'last_seen',
  osVersion: 'os_version',
  harnessVersion: 'harness_version',
  // Token-usage generated columns on audit_events (json_extract from attributes).
  inputTokens: 'input_tokens',
  outputTokens: 'output_tokens',
  cacheCreationInputTokens: 'cache_creation_input_tokens',
  cacheReadInputTokens: 'cache_read_input_tokens',
  model: 'model',
  provider: 'provider',
  // Meta data model — Source / Project
  url: 'url',
  // Meta data model — Inventory API (asset/file/override tables)
  assetType: 'asset_type',
  sub: 'sub',
  flagsJson: 'flags_json',
  metaJson: 'meta_json',
  trust: 'trust',
  toolsJson: 'tools_json',
  projectId: 'project_id',
  path: 'path',
  origin: 'origin',
  defaultAccess: 'default_access',
  findingsCount: 'findings_count',
  blockedAt: 'blocked_at',
  note: 'note',
  access: 'access',
  assetId: 'asset_id',
  provenance: 'provenance',
  // Meta data model — Audit event (timeline fact, self-ref tree)
  parentId: 'parent_id',
  rootSessionId: 'root_session_id',
  eventType: 'event_type',
  harnessId: 'harness_id',
  sourceProjectId: 'source_project_id',
  startedAt: 'started_at',
  endedAt: 'ended_at',
  priority: 'priority',
  // Meta data model — Classified data (class dimension)
  classKey: 'class',
  label: 'label',
  // Meta data model — Inspection definition / finding
  definition: 'definition',
  auditEventId: 'audit_event_id',
  inspectionDefinitionId: 'inspection_definition_id',
  classifiedDataId: 'classified_data_id',
  // Data Shares API — share_destination / share_endpoint / share_call_site /
  // egress_decision_override.
  host: 'host',
  networkJson: 'network_json',
  destinationId: 'destination_id',
  method: 'method',
  transport: 'transport',
  template: 'template',
  dataClass: 'data_class',
  endpointId: 'endpoint_id',
  project: 'project',
  projectKey: 'project_key',
  file: 'file',
  line: 'line',
  snippet: 'snippet',
  dynamic: 'dynamic',
  vendored: 'vendored',
  decision: 'decision',
  // Finding resolution — findings.finding_key + finding_resolution table.
  // (status/method/createdAt are reused from their existing entries above.)
  findingKey: 'finding_key',
  // Preserved first-detection time (epoch millis) — set once on a finding's
  // INSERT and never overwritten on the re-detection upsert, so MTTR / the
  // recently-resolved feed measure from when a finding was FIRST seen rather
  // than the latest re-scan's event (whose occurred_at the upsert overwrites).
  firstDetectedAt: 'first_detected_at',
  resolvedAt: 'resolved_at',
  evidence: 'evidence',
} as const;
