import { describe, expect, it } from 'vitest';

import * as barrel from '../src/index.ts';

// The barrel's exported symbol set is the package's public API and must not
// change during internal restructuring. Type-only exports are invisible at
// runtime; this snapshot pins the value exports.
const PUBLIC_VALUE_EXPORTS = [
  'AmbiguousExceptionIdError',
  'BLOCKED_DETECTIONS_RETENTION_MS',
  'BLOCKED_DETECTIONS_TTL_MS',
  'CONSENT_ABSENT',
  'DATA_DIR_MODE',
  'DATA_FILE_MODE',
  'DB_FILENAME',
  'DuplicateActiveExceptionError',
  'FileKeyProvider',
  'KeychainKeyProvider',
  'MAX_EGRESS_CALL_SITES_PER_PROJECT',
  'SecretVault',
  'SqliteActivityRepository',
  'SqliteAuditEventsRepository',
  'SqliteClassifiedDataRepository',
  'SqliteConfigInventoryRepository',
  'SqliteDetectionsRepository',
  'SqliteEventsRepository',
  'SqliteExceptionsRepository',
  'SqliteFindingsRepository',
  'SqliteInspectionDefinitionsRepository',
  'SqliteInspectionFindingsRepository',
  'SqliteInstalledPacksRepository',
  'SqliteInventoryAssetsRepository',
  'SqliteInventoryRepository',
  'SqlitePoliciesRepository',
  'SqlitePolicyCatalogRepository',
  'SqliteResolutionsRepository',
  'SqliteRuleProbeCacheRepository',
  'SqliteScanLedgerRepository',
  'SqliteSecretVaultRepository',
  'SqliteSecurityRepository',
  'SqliteSharesRepository',
  'SqliteSourceProjectRepository',
  'UNAVAILABLE',
  'VaultKeyEpochMissingError',
  'applyOnboarding',
  'base32Decode',
  'base32Encode',
  'bindingInput',
  'capWarnEraEnforcementOnce',
  'captureId',
  'classifiedDataId',
  'compareBinaryVersions',
  'computeFindingKey',
  'createKeyProvider',
  'dataDir',
  'dbPath',
  'defaultDataDir',
  'deriveSubkeys',
  'ensureDataDir',
  'ensureDataDirSync',
  'ensureLayoutDirSync',
  'fingerprintValue',
  'formatPointer',
  'inspectionDefinitionId',
  'inspectionFindingId',
  'inventoryId',
  'isCurrentKeyVersion',
  'keyStateOf',
  'keysDir',
  'llmCallId',
  'loadOrCreateFingerprintKey',
  'migrateLegacyLayout',
  'normalizeHost',
  'openLocalDatabase',
  'promptId',
  'readFingerprintKey',
  'readWorkspaceSettings',
  'rotateFingerprintKey',
  'settingsDir',
  'shareCallSiteId',
  'shareDestinationId',
  'shareEndpointId',
  'signPointer',
  'sourceProjectId',
  'tightenFile',
  'tightenPerms',
  'toolCallId',
  'verifyPointerTag',
  'writeOwnerOnlyFileSync',
];

describe('package barrel', () => {
  it('exports exactly the pinned public symbol set', () => {
    expect(Object.keys(barrel).sort()).toEqual(PUBLIC_VALUE_EXPORTS);
  });
});
