import { describe, expect, it } from 'vitest';

import * as barrel from '../src/index.ts';

// The barrel's exported symbol set is the package's public API and must not
// change during internal restructuring. Type-only exports are invisible at
// runtime; this snapshot pins the value exports.
const PUBLIC_VALUE_EXPORTS = [
  'ATTACHED_DERIVED_FILENAMES',
  'ATTACHED_FORWARD_DROPS_FILENAME',
  'ATTACHED_FORWARD_STATE_FILENAME',
  'ATTACHED_HISTORY_SYNC_STATE_FILENAME',
  'ATTACHED_SYNC_STATE_FILENAME',
  'AmbiguousExceptionIdError',
  'BLOCKED_DETECTIONS_RETENTION_MS',
  'BLOCKED_DETECTIONS_TTL_MS',
  'CONSENT_ABSENT',
  'DATA_DIR_MODE',
  'DATA_FILE_MODE',
  'DB_FILENAME',
  'DuplicateActiveExceptionError',
  'EXCEPTION_KEY_FILENAME',
  'FileKeyProvider',
  'FileLockError',
  'KeyUnclaimableError',
  'KeychainKeyProvider',
  'MAX_EGRESS_CALL_SITES_PER_PROJECT',
  'ManagedFieldError',
  'POLICY_CACHE_FILENAME',
  'PolicyFloorError',
  'SETTINGS_FILENAME',
  'STRUCTURAL_EVENT_TYPES',
  'SecretVault',
  'SqliteActivityRepository',
  'SqliteAuditEventsRepository',
  'SqliteClassifiedDataRepository',
  'SqliteConfigInventoryRepository',
  'SqliteDetectionsRepository',
  'SqliteEventsRepository',
  'SqliteExceptionsRepository',
  'SqliteFindingsRepository',
  'SqliteHistorySyncRepository',
  'SqliteInspectionDefinitionsRepository',
  'SqliteInspectionFindingsRepository',
  'SqliteInstalledPacksRepository',
  'SqliteInventoryAssetsRepository',
  'SqliteInventoryRepository',
  'SqlitePoliciesRepository',
  'SqlitePolicyCatalogRepository',
  'SqliteResolutionsRepository',
  'SqliteRuleProbeCacheRepository',
  'SqliteScanLedgerRepository',
  'SqliteSecretVaultRepository',
  'SqliteSecurityRepository',
  'SqliteSharesRepository',
  'SqliteSourceProjectRepository',
  'UNAVAILABLE',
  'UserGrantPolicyProvider',
  'VAULT_KEY_FILENAME',
  'VaultKeyEpochMissingError',
  'applyOnboarding',
  'base32Decode',
  'base32Encode',
  'bindingInput',
  'capHits',
  'capWarnEraEnforcementOnce',
  'captureId',
  'captureWireId',
  'classifiedDataId',
  'clearAttachmentDerivedState',
  'compareBinaryVersions',
  'computeFindingKey',
  'controlPlaneCredentialPath',
  'controlPlanePolicyFloor',
  'createKeyProvider',
  'createOwnerOnlyFileSync',
  'dataDir',
  'dbPath',
  'dbSidecars',
  'defaultDataDir',
  'deriveSubkeys',
  'ensureDataDir',
  'ensureDataDirSync',
  'ensureLayoutDirSync',
  'fingerprintValue',
  'formatPointer',
  'inspectionDefinitionId',
  'inspectionFindingId',
  'inventoryId',
  'isCurrentKeyVersion',
  'isSafeEndpoint',
  'keyStateOf',
  'keysDir',
  'linkTarget',
  'llmCallId',
  'loadOrCreateFingerprintKey',
  'lockedAmong',
  'managedContextOf',
  'managedSettingsPaths',
  'migrateLegacyLayout',
  'normalizeHost',
  'openLocalDatabase',
  'overlayManagedSettings',
  'packEnablementRefusal',
  'policyAssignmentRefusal',
  'promptId',
  'readCachedPolicyBundle',
  'readControlPlaneCredential',
  // The WIDE read. Exported deliberately and named so it cannot be reached by
  // accident: it returns a bearer credential, unlike the state reader beside
  // it, and belongs only to server-side callers.
  'readControlPlaneCredentialFile',
  'readControlPlaneCredentialState',
  'readEffectiveSettings',
  'readFingerprintKey',
  'readLocalHistoryPreview',
  'readManagedSettings',
  'readWorkspaceSettings',
  'removeControlPlaneCredential',
  'rotateFingerprintKey',
  'seedCaptureBacklogOwed',
  'settingsDir',
  'shareCallSiteId',
  'shareDestinationId',
  'shareEndpointId',
  'signPointer',
  'sourceProjectId',
  'storeTargets',
  'symlinkedStorePaths',
  'tightenFile',
  'tightenPerms',
  'toolCallId',
  'verifyPointerTag',
  'withFileLock',
  'withoutDroppedFiles',
  'writeControlPlaneCredential',
  'writeOwnerOnlyFileSync',
];

describe('package barrel', () => {
  it('exports exactly the pinned public symbol set', () => {
    expect(Object.keys(barrel).sort()).toEqual(PUBLIC_VALUE_EXPORTS);
  });
});
