// The rule packs shipped with every AKA plugin — the complete on-disk registry
// (repo-root rules/), one entry per pack, every rule the pack's manifest declares.
//
// GENERATED by scripts/gen-bundled-packs.mjs — do not edit by hand. The rule JSON
// is inlined into the hook scripts at build time (tsup bundles it via noExternal),
// so detection works with zero network and zero install steps. `packId` is the
// manifest id (also the prefix of every rule id, e.g. `core-pii/email`), so it
// joins back to findings.rule_id.
//
// Regenerate after adding/removing a rule or pack under rules/:
//   pnpm --filter @akasecurity/plugin-sdk gen:bundled-packs
//
// 7 packs / 101 rules.
/* eslint-disable simple-import-sort/imports */
import codeFlawsAuthJwtNoVerify from '../../../rules/code-flaws/auth-jwt-no-verify.json';
import codeFlawsAuthSslVerifyFalse from '../../../rules/code-flaws/auth-ssl-verify-false.json';
import codeFlawsCmdInjectExec from '../../../rules/code-flaws/cmd-inject-exec.json';
import codeFlawsCmdInjectNodeExec from '../../../rules/code-flaws/cmd-inject-node-exec.json';
import codeFlawsCmdInjectShell from '../../../rules/code-flaws/cmd-inject-shell.json';
import codeFlawsCryptoInsecureRandom from '../../../rules/code-flaws/crypto-insecure-random.json';
import codeFlawsCryptoWeakHashMd5 from '../../../rules/code-flaws/crypto-weak-hash-md5.json';
import codeFlawsCryptoWeakHashSha1 from '../../../rules/code-flaws/crypto-weak-hash-sha1.json';
import codeFlawsDeserJavaOis from '../../../rules/code-flaws/deser-java-ois.json';
import codeFlawsDeserPickle from '../../../rules/code-flaws/deser-pickle.json';
import codeFlawsDeserYamlUnsafe from '../../../rules/code-flaws/deser-yaml-unsafe.json';
import codeFlawsDevDebugEnabled from '../../../rules/code-flaws/dev-debug-enabled.json';
import codeFlawsDevPlaceholderSecret from '../../../rules/code-flaws/dev-placeholder-secret.json';
import codeFlawsDevWildcardCors from '../../../rules/code-flaws/dev-wildcard-cors.json';
import codeFlawsEvalDynamicExec from '../../../rules/code-flaws/eval-dynamic-exec.json';
import codeFlawsHardcodedPassword from '../../../rules/code-flaws/hardcoded-password.json';
import codeFlawsHardcodedSecretKey from '../../../rules/code-flaws/hardcoded-secret-key.json';
import codeFlawsPathTraversalJoin from '../../../rules/code-flaws/path-traversal-join.json';
import codeFlawsPathTraversalOpen from '../../../rules/code-flaws/path-traversal-open.json';
import codeFlawsPrototypePollutionMerge from '../../../rules/code-flaws/prototype-pollution-merge.json';
import codeFlawsRegexRedosBacktrack from '../../../rules/code-flaws/regex-redos-backtrack.json';
import codeFlawsSqlInjectConcatDot from '../../../rules/code-flaws/sql-inject-concat-dot.json';
import codeFlawsSqlInjectConcat from '../../../rules/code-flaws/sql-inject-concat.json';
import codeFlawsSqlInjectFormat from '../../../rules/code-flaws/sql-inject-format.json';
import codeFlawsSqlInjectInterp from '../../../rules/code-flaws/sql-inject-interp.json';
import codeFlawsSsrfUserUrl from '../../../rules/code-flaws/ssrf-user-url.json';
import codeFlawsXssDangerouslySet from '../../../rules/code-flaws/xss-dangerously-set.json';
import codeFlawsXssInnerHtml from '../../../rules/code-flaws/xss-inner-html.json';
import codeFlawsXssUnescapedRender from '../../../rules/code-flaws/xss-unescaped-render.json';
import coreCodeContextDbTableName from '../../../rules/core-code-context/db-table-name.json';
import coreCodeContextFeatureFlag from '../../../rules/core-code-context/feature-flag.json';
import coreCodeContextFilePath from '../../../rules/core-code-context/file-path.json';
import coreCodeContextInternalDomain from '../../../rules/core-code-context/internal-domain.json';
import coreCodeContextInternalIp from '../../../rules/core-code-context/internal-ip.json';
import coreCodeContextInternalUrl from '../../../rules/core-code-context/internal-url.json';
import coreCodeContextLocalhostRef from '../../../rules/core-code-context/localhost-ref.json';
import coreCodeContextStackTrace from '../../../rules/core-code-context/stack-trace.json';
import coreFinancialCreditCard from '../../../rules/core-financial/credit-card.json';
import coreFinancialCusip from '../../../rules/core-financial/cusip.json';
import coreFinancialCvv from '../../../rules/core-financial/cvv.json';
import coreFinancialIban from '../../../rules/core-financial/iban.json';
import coreFinancialPaypal from '../../../rules/core-financial/paypal.json';
import coreFinancialRoutingNumber from '../../../rules/core-financial/routing-number.json';
import coreFinancialSalary from '../../../rules/core-financial/salary.json';
import coreFinancialSwift from '../../../rules/core-financial/swift.json';
import corePhiBiometricRef from '../../../rules/core-phi/biometric-ref.json';
import corePhiGeneticData from '../../../rules/core-phi/genetic-data.json';
import corePhiGroupId from '../../../rules/core-phi/group-id.json';
import corePhiHipaaIdentifier from '../../../rules/core-phi/hipaa-identifier.json';
import corePhiIcd10Code from '../../../rules/core-phi/icd10-code.json';
import corePhiMemberId from '../../../rules/core-phi/member-id.json';
import corePhiMrn from '../../../rules/core-phi/mrn.json';
import corePhiNdcCode from '../../../rules/core-phi/ndc-code.json';
import corePiiDob from '../../../rules/core-pii/dob.json';
import corePiiDriversLicenseUs from '../../../rules/core-pii/drivers-license-us.json';
import corePiiEmail from '../../../rules/core-pii/email.json';
import corePiiHomeAddress from '../../../rules/core-pii/home-address.json';
import corePiiIpAddress from '../../../rules/core-pii/ip-address.json';
import corePiiMacAddress from '../../../rules/core-pii/mac-address.json';
import corePiiName from '../../../rules/core-pii/name.json';
import corePiiNationalId from '../../../rules/core-pii/national-id.json';
import corePiiPassportUs from '../../../rules/core-pii/passport-us.json';
import corePiiPhoneIntl from '../../../rules/core-pii/phone-intl.json';
import corePiiPhoneUs from '../../../rules/core-pii/phone-us.json';
import corePiiSsn from '../../../rules/core-pii/ssn.json';
import corePiiVin from '../../../rules/core-pii/vin.json';
import corePiiZip from '../../../rules/core-pii/zip.json';
import secretsInfraApiKeyHeader from '../../../rules/secrets-infra/api-key-header.json';
import secretsInfraBasicAuthHeader from '../../../rules/secrets-infra/basic-auth-header.json';
import secretsInfraBasicAuthUrl from '../../../rules/secrets-infra/basic-auth-url.json';
import secretsInfraBearerToken from '../../../rules/secrets-infra/bearer-token.json';
import secretsInfraDbConnectionString from '../../../rules/secrets-infra/db-connection-string.json';
import secretsInfraDockerConfigAuth from '../../../rules/secrets-infra/docker-config-auth.json';
import secretsInfraEnvKeyValue from '../../../rules/secrets-infra/env-key-value.json';
import secretsInfraGenericHighEntropySecret from '../../../rules/secrets-infra/generic-high-entropy-secret.json';
import secretsInfraJwtToken from '../../../rules/secrets-infra/jwt-token.json';
import secretsInfraKubeconfigToken from '../../../rules/secrets-infra/kubeconfig-token.json';
import secretsInfraPasswordField from '../../../rules/secrets-infra/password-field.json';
import secretsInfraPgpPrivateKey from '../../../rules/secrets-infra/pgp-private-key.json';
import secretsInfraSshPrivateKey from '../../../rules/secrets-infra/ssh-private-key.json';
import secretsAnthropicApiKey from '../../../rules/secrets/anthropic-api-key.json';
import secretsAwsAccessKey from '../../../rules/secrets/aws-access-key.json';
import secretsAwsSecretKey from '../../../rules/secrets/aws-secret-key.json';
import secretsAzureConnectionString from '../../../rules/secrets/azure-connection-string.json';
import secretsCloudflareApiKey from '../../../rules/secrets/cloudflare-api-key.json';
import secretsDatadogKey from '../../../rules/secrets/datadog-key.json';
import secretsDigitaloceanToken from '../../../rules/secrets/digitalocean-token.json';
import secretsDiscordToken from '../../../rules/secrets/discord-token.json';
import secretsGcpServiceAccount from '../../../rules/secrets/gcp-service-account.json';
import secretsGithubPat from '../../../rules/secrets/github-pat.json';
import secretsGitlabToken from '../../../rules/secrets/gitlab-token.json';
import secretsHerokuApiKey from '../../../rules/secrets/heroku-api-key.json';
import secretsNpmToken from '../../../rules/secrets/npm-token.json';
import secretsOpenaiApiKey from '../../../rules/secrets/openai-api-key.json';
import secretsPulumiAccessToken from '../../../rules/secrets/pulumi-access-token.json';
import secretsSendgridKey from '../../../rules/secrets/sendgrid-key.json';
import secretsSlackToken from '../../../rules/secrets/slack-token.json';
import secretsStripeLiveKey from '../../../rules/secrets/stripe-live-key.json';
import secretsTerraformCloudToken from '../../../rules/secrets/terraform-cloud-token.json';
import secretsTwilioKey from '../../../rules/secrets/twilio-key.json';
import secretsVaultToken from '../../../rules/secrets/vault-token.json';

export interface BundledPack {
  packId: string;
  name: string;
  version: string;
  rawRules: unknown[];
}

export const BUNDLED_PACKS: readonly BundledPack[] = [
  {
    packId: 'code-flaws',
    name: 'Code Security Flaws',
    version: '0.1.0',
    rawRules: [
      codeFlawsSqlInjectConcat,
      codeFlawsSqlInjectConcatDot,
      codeFlawsSqlInjectFormat,
      codeFlawsSqlInjectInterp,
      codeFlawsCmdInjectShell,
      codeFlawsCmdInjectExec,
      codeFlawsCmdInjectNodeExec,
      codeFlawsXssInnerHtml,
      codeFlawsXssDangerouslySet,
      codeFlawsXssUnescapedRender,
      codeFlawsDeserPickle,
      codeFlawsDeserYamlUnsafe,
      codeFlawsDeserJavaOis,
      codeFlawsHardcodedPassword,
      codeFlawsHardcodedSecretKey,
      codeFlawsDevDebugEnabled,
      codeFlawsDevPlaceholderSecret,
      codeFlawsDevWildcardCors,
      codeFlawsAuthSslVerifyFalse,
      codeFlawsAuthJwtNoVerify,
      codeFlawsPathTraversalOpen,
      codeFlawsPathTraversalJoin,
      codeFlawsCryptoWeakHashMd5,
      codeFlawsCryptoWeakHashSha1,
      codeFlawsCryptoInsecureRandom,
      codeFlawsPrototypePollutionMerge,
      codeFlawsEvalDynamicExec,
      codeFlawsSsrfUserUrl,
      codeFlawsRegexRedosBacktrack,
    ],
  },
  {
    packId: 'core-code-context',
    name: 'Code Context',
    version: '0.1.0',
    rawRules: [
      coreCodeContextInternalIp,
      coreCodeContextLocalhostRef,
      coreCodeContextInternalDomain,
      coreCodeContextFilePath,
      coreCodeContextStackTrace,
      coreCodeContextInternalUrl,
      coreCodeContextFeatureFlag,
      coreCodeContextDbTableName,
    ],
  },
  {
    packId: 'core-financial',
    name: 'Financial Information',
    version: '0.1.0',
    rawRules: [
      coreFinancialCreditCard,
      coreFinancialIban,
      coreFinancialRoutingNumber,
      coreFinancialSwift,
      coreFinancialCvv,
      coreFinancialCusip,
      coreFinancialPaypal,
      coreFinancialSalary,
    ],
  },
  {
    packId: 'core-phi',
    name: 'Protected Health Information',
    version: '0.1.0',
    rawRules: [
      corePhiMrn,
      corePhiHipaaIdentifier,
      corePhiMemberId,
      corePhiGroupId,
      corePhiIcd10Code,
      corePhiNdcCode,
      corePhiGeneticData,
      corePhiBiometricRef,
    ],
  },
  {
    packId: 'core-pii',
    name: 'Core PII',
    version: '0.2.0',
    rawRules: [
      corePiiEmail,
      corePiiSsn,
      corePiiPhoneUs,
      corePiiPhoneIntl,
      corePiiIpAddress,
      corePiiDob,
      corePiiDriversLicenseUs,
      corePiiPassportUs,
      corePiiHomeAddress,
      corePiiName,
      corePiiVin,
      corePiiMacAddress,
      corePiiNationalId,
      corePiiZip,
    ],
  },
  {
    packId: 'secrets',
    name: 'Secrets & Credentials',
    version: '0.1.0',
    rawRules: [
      secretsAwsAccessKey,
      secretsAwsSecretKey,
      secretsGcpServiceAccount,
      secretsAzureConnectionString,
      secretsOpenaiApiKey,
      secretsAnthropicApiKey,
      secretsStripeLiveKey,
      secretsSlackToken,
      secretsDiscordToken,
      secretsSendgridKey,
      secretsTwilioKey,
      secretsGitlabToken,
      secretsDigitaloceanToken,
      secretsDatadogKey,
      secretsNpmToken,
      secretsHerokuApiKey,
      secretsCloudflareApiKey,
      secretsPulumiAccessToken,
      secretsTerraformCloudToken,
      secretsVaultToken,
      secretsGithubPat,
    ],
  },
  {
    packId: 'secrets-infra',
    name: 'Infrastructure Secrets',
    version: '0.1.0',
    rawRules: [
      secretsInfraSshPrivateKey,
      secretsInfraDbConnectionString,
      secretsInfraJwtToken,
      secretsInfraBasicAuthUrl,
      secretsInfraBasicAuthHeader,
      secretsInfraPgpPrivateKey,
      secretsInfraBearerToken,
      secretsInfraEnvKeyValue,
      secretsInfraPasswordField,
      secretsInfraDockerConfigAuth,
      secretsInfraKubeconfigToken,
      secretsInfraApiKeyHeader,
      secretsInfraGenericHighEntropySecret,
    ],
  },
];
